name: Python application

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        py_ver: ["3.7", "3.8", "3.9", "3.11.0-alpha.2"]
    steps:
    - uses: actions/checkout@v2.4.0
#     - name: Set up Python
#       uses: actions/setup-python@v2.2.2
#       with:
#         python-version: ${{ matrix.py_ver }}
    - run: |
        sudo apt update
        sudo apt install software-properties-common
        sudo add-apt-repository ppa:deadsnakes/ppa
        # sudo apt-get purge --auto-remove python3 python3-dev python3-pip python3-venv
        
        sudo apt install python3.10
        # sudo ln -s /usr/bin/python3.10 /usr/bin/python
        # sudo ln -s /usr/bin/python3.10 /usr/bin/python3
        sudo update-alternatives --install /usr/bin/python python /usr/bin/python3.10 1
        echo 'alias python="python3.10"' >> ~/.bashrc
        echo 'alias python="python3.10"' >> ~/.bash_aliases
        python --version
        python3 --version
        python3.10 --version
        which python3
        which python3.10
    - name: Install Ubuntu dependencies
      run: >
        sudo apt-get update -qq && sudo apt-get install -qq --no-install-recommends
        gir1.2-gtk-3.0 libgirepository1.0-dev
#     - name: Install Poetry
#       uses: abatilo/actions-poetry@v2.1.4
    - run: |
        sudo update-alternatives --config python
        python3.10 --version
        python --version
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3.10 -
        export PATH="$HOME/.poetry/bin:$PATH"
        poetry env use python3.10
        poetry config virtualenvs.create false
        poetry env info
        poetry install
        xvfb-run pytest
#     - name: Turn off Virtualenvs
#       run: poetry config virtualenvs.create false
#     - name: Install Python Dependencies
#       run: poetry install
#     # - name: Setup tmate session
#     #   uses: mxschmitt/action-tmate@v1
#     - name: Test with Pytest
#       run: |
#         # export DISPLAY=':99.0'
#         export DISPLAY=:0.0
#         # sudo apt-get remove xvfb
#         # sudo apt-get install -y xvfb
#         xvfb-run pytest
#         # pytest
