name: Python application

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        py_ver: ["3.7", "3.8", "3.9", "3.11.0-alpha.2"]
    steps:
    - uses: actions/checkout@v2.4.0
    - name: Set up Python
      uses: actions/setup-python@v2.2.2
      with:
        python-version: ${{ matrix.py_ver }}
    - name: Install Ubuntu dependencies
      run: >
        sudo apt-get update -qq && sudo apt-get install -qq --no-install-recommends
        gir1.2-gtk-3.0 libgirepository1.0-dev
    - name: Install Poetry
      uses: abatilo/actions-poetry@v2.1.4
    - name: Turn off Virtualenvs
      run: poetry config virtualenvs.create false
    - name: Install Python Dependencies
      run: poetry install
    # - name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v1
    - name: Test with Pytest
      run: |
        # export DISPLAY=':99.0'
        # xvfb-run pytest
        pytest
